sudo: required

language: node

services:
  - docker

script: docker run --name travis-test marcocab/docker-app-sales /bin/sh -c "ionic cordova platform add android && ionic cordova build android"

after_script:
  - docker stop travis-test